# Generated by Django 4.1.5 on 2023-01-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_comment_comms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stuff.stuff'),
        ),
    ]
