# Generated by Django 4.1.5 on 2023-01-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_hashtag_stuff_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='hashtags',
            new_name='categories',
        ),
    ]
